# Generated by Django 5.2.7 on 2025-11-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stridetastic_api", "0002_publisherperiodicjob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="node",
            name="reactive_latency_ms",
        ),
        migrations.RemoveField(
            model_name="node",
            name="reactive_reachable",
        ),
        migrations.AddField(
            model_name="node",
            name="latency_ms",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Round-trip latency in milliseconds observed for the most recent probe response.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="latency_reachable",
            field=models.BooleanField(
                blank=True,
                help_text="Indicates whether the most recent latency probe received a response.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="NodeLatencyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the probe result was recorded.",
                    ),
                ),
                (
                    "probe_message_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Mesh packet identifier associated with this probe when available.",
                        null=True,
                    ),
                ),
                (
                    "reachable",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether the probe determined the node to be reachable.",
                        null=True,
                    ),
                ),
                (
                    "latency_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Round-trip latency measurement in milliseconds when available.",
                        null=True,
                    ),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when a response was received for this probe.",
                        null=True,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        help_text="Node associated with the probe result.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latency_history",
                        to="stridetastic_api.node",
                    ),
                ),
            ],
            options={
                "verbose_name": "Node Latency History",
                "verbose_name_plural": "Node Latency History",
                "ordering": ["time"],
            },
        ),
        migrations.DeleteModel(
            name="NodeReactiveLatencyHistory",
        ),
    ]
