# Generated by Django 5.2.7 on 2025-12-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stridetastic_api", "0003_remove_node_reactive_latency_ms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="is_low_entropy_public_key",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the stored public key matches a known low-entropy hash.",
            ),
        ),
    ]
