# Generated by Django 5.2.10 on 2026-01-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stridetastic_api", "0009_keepalive_publish_config"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interface",
            options={
                "ordering": ["name"],
                "verbose_name": "Interface",
                "verbose_name_plural": "Interfaces",
            },
        ),
        migrations.RemoveField(
            model_name="interface",
            name="display_name",
        ),
        migrations.AddField(
            model_name="interface",
            name="interface_type",
            field=models.CharField(
                choices=[
                    ("MQTT", "MQTT"),
                    ("SERIAL", "Serial"),
                    ("TCP", "TCP (Network)"),
                ],
                default="MQTT",
                help_text="Type of the interface (MQTT / SERIAL / TCP).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="interface",
            name="name",
            field=models.CharField(
                help_text="Unique name for this interface instance.",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="publisherperiodicjob",
            name="payload_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Message"),
                    ("position", "Position"),
                    ("nodeinfo", "Node Info"),
                    ("traceroute", "Traceroute"),
                    ("telemetry", "Telemetry"),
                ],
                max_length=32,
            ),
        ),
    ]
